apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
  labels:
    project: roboshop
    environment: dev
    owner: mramsudheer
  annotations:
    purpose: "This namespace is for Roboshop application"